-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 02-01-2020 a las 16:43:55
-- Versión del servidor: 10.4.10-MariaDB
-- Versión de PHP: 7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `db_cubiertas`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_products_cb`
--

CREATE TABLE `tbl_products_cb` (
  `id_product_cb` int(11) NOT NULL,
  `name_product_cb` varchar(250) COLLATE utf8_spanish2_ci NOT NULL,
  `cat_product_cb` int(2) NOT NULL,
  `desc_product_cb` text COLLATE utf8_spanish2_ci NOT NULL,
  `cant_images` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

--
-- Volcado de datos para la tabla `tbl_products_cb`
--

INSERT INTO `tbl_products_cb` (`id_product_cb`, `name_product_cb`, `cat_product_cb`, `desc_product_cb`, `cant_images`) VALUES
(1, 'Panel Cn-4', 1, '<p>Panel trapezoidal, utilizado para cubierta y revestimiento el cual permite soportar cargas entre los distanciamientos de costaneras gracias a sus nervios rigidizantes. Panel CN-4 Terminación en pre-pintado y zinc-alum. Presentación curva y contracurva. Panel CN-4 Traslúcida FRP disponibles con la misma geometría para solucionar la luminosidad requerida del proyecto.</p><h3>Características técnicas</h3><p>Avance útil: 1000mm Espesores: 0.35 mm / 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p><h3>Características del panel</h3><p>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n<li>El avance útil permite un mayor ahorro en m2 instalado</li>\r\n<li>La instalación de cubiertas</li>\r\n<li>Revestimiento simple y rápida</li>\r\n<li>Solución curvas y contracurvas</li>\r\n<li>Radio mínimo curvatura 240mm- Largos a pedido (hasta 18mt) solución largo continuo</li>	\r\n</ul>			\r\n</p><h3>Recubrimiento</h3><p>\r\nZinc-alum aplicado en ambas caras\r\nSegún norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 3),
(2, 'Panel Cn-6', 1, '<p>Panel trapezoidal, utilizado para cubierta y revestimiento el cual permite soportar cargas entre los distanciamientos\r\n    de costaneras gracias a sus nervios rigidizantes. Panel CN-6 Terminación en prepintado y zinc-alum. Presentación\r\n    curva y contracurva. Panel CN-6 Traslúcida FRP disponibles con la misma geometría para solucionar la luminosidad\r\n    requerida del proyecto.</p>\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 910mm Espesores: 0.35 mm / 0.4mm / 0.5mm / 0.6mm / 0.8mm Largos: 0.5mt a 18.00 mt (largos especiales, consultar) Terminación: zinc-alum, prepintado y galvanizado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>La instalación de cubierta.</li>\r\n    <li>Revestimiento es simple y rápida.</li>\r\n    <li>Solución curvas y contracurvas.</li>\r\n    <li>Radio mínimo curvatura 240mm.</li>\r\n    <li>Largos a pedido (hasta 18mt) solución largo continuo</li>\r\n    <li>Cubierta y revestimientos para naves industriales, galpones.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 2),
(3, 'Panel Altex 6', 1, '<p>Panel trapezoidal, utilizado para cubierta y revestimiento el cual permite soportar cargas entre los distanciamientos\r\n    de costaneras gracias a sus nervios rigidizantes. Panel ALTEX-6 Terminación en prepintado y zinc-alum. Presentación\r\n    curva y contracurva. Panel ALTEX-6 Traslúcida FRP disponible con la misma geometría para solucionar la luminosidad\r\n    requerida del proyecto.</p>\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 980mm Espesores: 0.35mm / 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>La instalación de cubierta.</li>\r\n    <li>Revestimiento es simple y rápida.</li>\r\n    <li>Solución curvas y contracurvas.</li>\r\n    <li>Radio mínimo curvatura 240mm.</li>\r\n    <li>Largos a pedido (hasta 18mt) solución largo continuo.</li>\r\n    <li>Cubierta y revestimientos para naves industriales, galpones, bodegas y colegios.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(4, 'Panel Cn-2', 1, '<p>Panel utilizado para cubierta, permitiendo soportar cargas entre los distanciamientos de costaneras. Es una solución\r\n    para baja pendiente de cubierta, que tiene la opción de poder fabricarse en terreno en largos continuos según la\r\n    necesidad del proyecto. Panel CN-2 Terminación en prepintado y zinc-alum. Panel CN-2 Traslúcida FRP disponibles con\r\n    la misma geometría para solucionar la luminocidad requerida del proyecto.</p>\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 450mm Espesores: 0.35 mm / 0.4mm / 0.5mm / 0.6mm. Largos: 0.5mt a 18.00 mt (largos especiales, consultar) Terminación: zinc-alum y prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Permite minimizar los riesgos de posibles filtraciones al tener una baja pendiente.</li>\r\n    <li>Se fabrica en largos continuos a solicitud del cliente.</li>\r\n    <li>Superficie de facil y rapida limpieza.</li>\r\n    <li>Se considera para cubiertas con baja pendiente.</li>\r\n    <li>Posibilidad de fabricar en terreno en largos continuos.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(5, 'Panel Ondulado Cn-1020', 1, '<p>Plancha de acero acanalada de gran ancho útil. Utilizada para cubiertas de viviendas, cobertizos, pequeños galpones,\r\n    revestimientos laterales y cierres perimetrales. Panel Ondulado CN-1020 Terminación en prepintado y zinc-alum. Panel\r\n    Ondulado CN-1020 Traslúcida FRP disponible con la misma geometría para solucionar la luminocidad requerida del\r\n    proyecto.</p>\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 1020mm Espesores: 0.35 mm / 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>El avance útil permite un mayor ahorro en m2 instalado.</li>\r\n    <li>Resistencia mecánica.</li>\r\n    <li>La instalación de cubiertas.</li>\r\n    <li>Revestimiento es simple y rápida</li>\r\n    <li>Largos a pedido (hasta 18 mts.) solución largo continuo.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(6, 'Panel Cn-900', 1, '<p>Panel trapezoidal, utilizado para cubierta y revestimientos permitiendo soportar cargas entre los distanciamientos de\r\n    costaneras gracias a sus nervios rigidizantes. Panel CN-900 Terminación en prepintado y zinc-alum. Panel CN-900\r\n    Traslúcido FRP disponible con la misma geometría para solucionar la luminocidad requerida del proyecto.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 900mm Espesores: 0.35mm / 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Panel trapezoidal con 6 nervios de altura 35mm.</li>\r\n    <li>Utilizado principalmente en revestimiento.</li>\r\n    <li>Este panel es mayoritariamente utilizado en bodegas industriales, galpones, colegios y un sinnúmero de construcciones. </li>\r\n    <li>Se fabrica en acero zinc-alum y prepintado.</li>\r\n    <li>Resistencia mecánica.</li>\r\n    <li>La instalación de cubierta.</li>\r\n    <li>Revestimiento simple y rápida.</li>\r\n    <li>Largos a pedido (hasta 18 mts.) solución largo continuo.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(7, 'Placa Colaborante Cn-6', 1, '<p>Panel estructural fabricado en acero galvanizado, calidad G-90 el cual en conjunto con el hormigón permite la\r\n    construcción de losas en menor plazo, con un menor volumen de hormigón y reducción del uso de alzaprimas. Acero:\r\n    Calidad Estructural Grado 37 G90: 2.600 kg/cm2). Recubrimiento: Galvanizado, aplicado en ambas caras según norma de\r\n    fabricación ASTM A653 M07 / calidad G-90 (275 gr/m2). Terminación: Natural.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 910mm Espesores: 0.8mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: galvanizado</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Permite hacer cortes, uniones, aberturas facilitando adicionalmente la instalación de ductos y cabrería en el cielo.</li>\r\n    <li>Panel estructural fabricado en acero galvanizado calidad g-90, el cual en conjunto con el hormigón permiten la construcción de losas en menor plazo, con un menor volumen de hormigón y reducción del uso de alzaprimas.</li>\r\n    <li>Se utiliza en todo tipo de construcción.</li>\r\n</ul>', 2),
(8, 'Placa Colaborante Cn Deck', 1, '<p>Panel estructural fabricado en acero galvanizado, calidad G-90 el cual en conjunto con el hormigón permite la\r\n    construcción de losas en menor plazo, con un menor volumen de hormigón y reducción del uso de alzaprimas. Placa\r\n    Colaborante CN-DECK Terminación Galvanizado e=0.8mm Acero: Calidad Estructural Grado 37 G90 : 2.600 kg/cm2).\r\n    Recubrimiento: Zinc Galvanizado, aplicado en ambas caras según norma fabricación ASTM A653 M07 / calidad G-90 (275\r\n    gr/m2). Terminación: Natural.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance util: 950mm Espesores: 0.8mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: galvanizado</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Permite hacer cortes, uniones, aberturas facilitando adicionalmente la instalacion de ductos y cablería en el cielo.</li>\r\n    <li>Panel estructural fabricado en acero galvanizado calidad g-90, el cual en conjunto con el hormigón permiten la\r\n        construcción de losas en menor plazo, con un menor volumen de hormigón y reducción del uso de alzaprimas.</li>\r\n    <li>Se utiliza en todo tipo de construcción.</li>\r\n    </ul>', 2),
(9, 'Panel Cn-3', 1, '<p>Panel trapezoidal utilizado para cubierta y revestimiento el cual permite soportar cargas entre los distanciamientos\r\n    de costaneras gracias a sus nervios rigidizantes. Panel CN-3 Terminación en prepintado y zinc-alum. Presentación\r\n    curva y contracurva. Panel CN-3 Traslúcida FRP disponibles con la misma geometría para solucionar la luminocidad\r\n    requerida del proyecto. Sus formas hacen de una buena alternativa de estética y permite revestimientos horizontales\r\n    y verticales.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 1080mm Espesores: 0.35 mm / 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>El avance útil permite un mayor ahorro en m2 instalado.</li>\r\n    <li>Instalación de cubiertas.</li>\r\n    <li>Revestimiento simple y rápida.</li>\r\n    <li>Solución curvas y contracurvas.</li>\r\n    <li>Radio mínimo curvatura 240mm.</li>\r\n    <li>Largos a pedido (hasta 18mt) solución largo continuo.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(10, 'Panel Cn-18', 1, '<p>Panel utilizado para cubierta, permitiendo soportar cargas entre los distanciamientos de costaneras. Es una solución\r\n    para baja pendiente de cubierta, que tiene la opción de poder fabricarse en terreno en largos continuos según la\r\n    necesidad del proyecto. Panel CN-18 Terminación en prepintado y zinc-alum. Panel CN-18 Traslúcida FRP disponible con\r\n    la misma geometría para solucionar la luminocidad requerida del proyecto.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil : 457mm Espesores: 0.35 mm / 0.4 mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mt (largo continuo) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Permite minimizar los riesgos de posibles filtraciones al tener una baja pendiente.</li>\r\n    <li>Se fabrica en largos continuos a solicitud del cliente.</li>\r\n    <li>Resistencia mecánica.</li>\r\n    <li>Superficie de fácil y rápida limpieza.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 2),
(11, 'Panel Cn-8', 1, '<p>Panel trapezoidal utilizado en revestimientos permitiendo un efecto estético según proyecto requerido. Presentación\r\n    forma horizontal y vertical. Panel CN-8 Terminación en prepintado y Zinc Alum. Panel CN-8 Traslúcida FRP disponibles\r\n    con la misma geometría para solucionar la luminocidad requerida del proyecto.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 1000mm Espesores: 0.4mm / 0.5mm / 0.6mm. Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Panel cn-8 diseñado para revestimientos, galpones, centros comerciales.</li>\r\n    <li>Instalación en forma vertical u horizontal.</li>\r\n    <li>Se fabrica en largos a solicitud del cliente.</li>\r\n    <li>Su geometría esta constituida por 8 nervios rigidizantes permitiendo un efecto arquitectónico según requerimientos del proyecto.</li>\r\n    <li>Instalación rápida y modular, gracias a su avance útil de 1.00 mt.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(12, 'Panel Cn-6V', 1, '<p>Cubierta y revestimiento de acero de largo continuo, con claras ventajas estructurales y de estanqueidad. Su sistema\r\n    de traslapo lateral corta la filtración de agua por capilaridad. - Diseño en diferentes tonalidades proporciona un\r\n    carácter estético superior. - Gran vida útil de la cubierta ya que es fabricada con pintura. - Su gran avance útil y\r\n    formato de largo continuo, favorece la velocidad de montaje de la cubierta. - Dado su bajo peso, se obtiene como\r\n    ventaja un mayor ahorro en la estructura soportante y una menor carga sísmica, ya que el peso de la cubierta es un\r\n    10% menor con respecto a su símil de acero.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 1020mm Espesores: 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>El avance útil permite un mayor ahorro en m2 instalado.</li>\r\n    <li>Resistencia mecánica.</li>\r\n    <li>La instalación de cubiertas.</li>\r\n    <li>Revestimiento simple y rapida.</li>\r\n    <li>Largos a pedido (hasta 18 mts.) solución largo continuo.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 2),
(13, 'Panel Aislado Cn-4Pol', 1, '<p>Panel aislado de acero estructural de cuatro trapecios, construido por dos láminas de acero con núcleo de\r\n    poliestireno expandido, adherido a ambas laminas metálicas. Panel CN-4 POL Terminación en prepintado y zinc-alum.\r\n    Panel CN-4 POL Traslúcidas FRP disponible con la misma geometría para solucionar la luminosidad requerida del\r\n    proyecto. Alternativa cara inferior polipropileno blanco o foil aluminio.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 1000mm Espesores (mm) : 30/40/50/60/70/75 /80/90/100/120/150. Largos: o.5mt a 13.00 mt (largos\r\n    especiales, consultar) Terminación superior: zincalum o prepintado Terminación inferior: zinc-alum, prepintado,\r\n    polipropileno blanco aluminio</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>El avance útil permite un mayor ahorro en m2 instalado.</li>\r\n    <li>Resistencia mecánica.</li>\r\n    <li>La instalación de cubiertas.</li>\r\n    <li>Revestimiento simple y rapida.</li>\r\n    <li>Largos a pedido (hasta 13 mts.) solución largo continuo.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(14, 'Panel Aislado Cn-Pol', 1, '<p>Panel constituido por dos planchas de acero y núcleo aislante de poliestireno expandido el cual es utilizado para cámaras frigoríficas como también para muros divisorios interiores.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Acero: Calidad Estructural Recubrimiento: Zinc Aluminio, aplicado en ambas caras según fabricación ASTM A792 M08. Recubrimiento AZ150 (150gr/m2). Terminación: Zinc Alum ó Prepintado. Núcleo: Nucleo de poliestireno expandido, auto extinguible. Densidad de 15 o 20 Kg/m3.\r\n</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Excelente comportamiento estructural.</li>\r\n    <li>Solución de terminación, sobre estructuras de madera, metálicas, albañilería y hormigón.</li>\r\n    <li>Instalación rápida y simple.</li>\r\n    <li>Sus dimensiones permiten un fácil traslado y manipulación.</li>\r\n    <li>Gran resistencia a la humedad, corrosión y medio ambiente.</li>\r\n    <li>El acabado de la superficie es homogénea y la terminación considera nervaduras o liso.</li>\r\n    <li>Los largos a pedido permiten soluciones de largo continuo.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(15, 'Panel Aislado Cn-4 Pur', 1, '<p>Panel aislado de acero estructural de cuatro trapecios, construido por dos láminas de acero con núcleo de poliuretano\r\n    de alta densidad, adherido a ambas laminas metálicas. Panel CN-4 PUR Terminación en prepintado y zinc-alum. Panel\r\n    CN-4 PUR Traslúcida FRP disponible con la misma geometría para solucionar la luminocidad requerida del proyecto.\r\n    Alternativa cara inferior pollpropileno Blanco o foil aluminio</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 1000mm Espesores: 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 14.00 mt (largos especiales, consultar)\r\n    Terminación superior: zinc-alum o prepintado Terminación inferior: zinc-alum, prepintado, polipropileno. Espesores\r\n    (mm): 30 / 40 / 50 / 60 / 70 / 75 / 80 / 90 / 100.\r\n</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Está constituido por dos chapas metálicas, con núcleo de poliuretano de alta densidad adherido a ambas chapas (tipo sandwich).</li>\r\n    <li>El poliuretano es un aislante térmico. Que al estar bajo cubierta reduce la condensación para estos casos.</li>\r\n    <li>Alta resistencia mecánica al estar entre dos láminas metálicas permite cargas en distanciamientos de costaneras.</li>\r\n    <li>Se utiliza para cubiertas y revestimientos galpones comerciales-industriales acondicionamiento térmico.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(16, 'Insumos', 1, '<p>El Panel CN18 es un panel de largo continuo para ser emballetado en obras de baja pendiente. Con ello se evita los\r\n    traslapos longitudinales y las fijaciones se instalan de manera oculta. Dichas fijaciones absorben las deformaciones\r\n    de las estructuras como las dilataciones producidas sobre la cubierta. Los Clip se componen de lo siguiente: CLIP\r\n    FIJO Se fija de manera oculta sobre la costanera y se engancha con el Panel CN18. Es recomendado para aguas menores\r\n    a 12 metros de largo. CLIP MÓVIL Está compuesto por dos piezas. La primera que se fija sobre costanera y la segunda\r\n    sirve para enganchar la base con el Panel CN18 permitiendo dejar la cubierta a prueba de dilataciones y\r\n    contracciones de acero sobre ella. Es recomendado para aguas mayores a 12 metros de largo.</p>\r\n\r\n<h3>Gancho Omega</h3>\r\n<p>El gancho Omega es un elemento de fijación estructural que va fijado en sus dos aletas con pernos autoperforantes\r\n    permitiendo una fijación más fuerte en las zonas geográficas de vientos altos superiores a los 70 km/H. Unas de las\r\n    características principales de este elemento de fijación es mantener la forma del panel trapezoidal impidiendo que\r\n    se produzca un pandeo provocado por la instalación del tornillo.\r\n</p>\r\n\r\n<h3>Golillas K</h3>\r\n<p>Cuando instalamos un panel trapezoidal es muy importante hacerlo de manera correcta y con los implementos\r\n    correspondientes para lograr los resultados esperados, por lo que se recomienda instalar una “golilla K” entre el\r\n    tornillo autoperforante y el nervio del trapecio.</p>', 3),
(17, 'Panel Cn Super Cuadro', 2, '<p>El Panel Arquitectónico CN-Cuadrado está diseñado para ser usado como revestimiento tanto en fachadas exteriores como\r\n    interiores, a su vez permite ser acomodado en forma horizontal como vertical. Ademas da soluciones arquitectónicas\r\n    para cielos y marquesinas. Este panel puede ser solicitado con microperforaciones que son usadas en cortes de\r\n    iluminación artificial, natural y solar. También como método de aireación.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 200mm Espesores: 0.4mm / 0.5mm Largos: 0.5mts a 6.0 mts. (largos especiales, consultar) Terminación: Zinc-Alum o Prepintado.\r\n</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Instalación fijación oculta, permite una superficie limpia y estética.</li>\r\n    <li>Uso en revestimientos.</li>\r\n    <li>Largos a pedido, consultar.</li>\r\n    <li>Permite un revestimiento horizontal y vertical.</li>\r\n    <li>Solución perforada para quiebravista.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(18, 'Panel Cn-Cuadro', 2, '<p>Panel arquitectónico mayormente usado en fachadas, cortavistas y terminaciones. El panel es una buena alternativa\r\n    estética. Está diseñado con un sistema de traslapo que permite su instalación tanto de manera horizontal como\r\n    vertical para dar soluciones arquitectónicas limpias sin fijaciones a la vista . Además puede ser solicitado con\r\n    microperforaciones para dar solución a cortes de iluminación artificial, natural y solar.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 200mm Espesores: 0.5mm Largos: 0.5mts a 6.0 mts. (largos especiales, consultar) Terminación: Prepintado.\r\n</p>\r\n\r\n<h3>Caracteristicas del panel</h3>\r\n<ul style=\"list-style: disc; margin: 20px;\">\r\n    <li>Instalación fijación oculta, permite una superficie limpia y estética.</li>\r\n    <li>Uso en revestimientos.</li>\r\n    <li>Largos a pedido, consultar.</li>\r\n    <li>Permite un revestimiento horizontal y vertical.</li>\r\n    <li>Solución perforada para quiebravista.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>', 3),
(19, 'Panel Perforado', 2, '<p>La aplicación de Paneles Perforados de línea continua de Cubiertas Nacionales permite realizar en todas sus\r\n    geometrías variedad de perforaciones en sus productos industriales como de vivienda, entregando un atractivo visual\r\n    de revestimiento exterior e interior. Los Paneles Perforados de Cubiertas Nacionales son fabricados según longitudes\r\n    y necesidades de cada cliente, aportando menos cantidad de traslapos y obteniendo mejor iluminación, sombras y\r\n    ventilaciones según cada proyecto.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>CN-4 / CN-6 / Altex 6 / Ondulado 1020mm CN-8 / CN-900 / Planchas lisas / CN-3 Arquitectónicos / Celosía CN-40 / CN-23\r\n    Ondulado 3/4 / Acanalado 5V</p>\r\n\r\n<h3>Ventajas</h3>\r\n<p>Los Paneles Perforados de línea continua de Cubiertas Nacionales son fabricados en planta, garantizando con\r\n    maquinaria de última generación una mayor durabilidad y calidad del producto. Los Paneles Perforados de Cubiertas\r\n    Nacionales, pueden ser fabricados en cualquier geometría de nuestras líneas de productos.</p>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras, según norma fabricación ASTM A792 M08, calidad AZ-150 (150gr/m2)</p>\r\n\r\n<h3>Pre-pintados</h3>\r\n<p>Prepintados pintura de poliéster con espesor de 15 a 20 micras aplicado en una cara de la línea continua a bases de resinas sintéticas, pigmentos y aditivos que proporcionan un acabado de alta calidad.</p>\r\n\r\n<h3>Aplicaciones</h3>\r\n<p>Los paneles perforados son utilizados para el contra solar, acústico y ventilación, como también en cielo falso y traslúcidas de todo tipo de proyectos industriales y habitacionales.</p>', 2),
(20, 'Panel Cn Wave', 2, '<p>Panel arquitectónico mayormente usado en fachadas, cortavistas y terminaciones. El panel es una buena alternativa\r\n    estética y permite revestimientos horizontales y verticales. Este panel puede ser solicitado con microperforaciones\r\n    que permite ser usado en cortes de iluminación artificial, natural y solar.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil : 270mm Espesores: 0.5mm. Largos: 0.5 mt. a 6.0 mt. (Largos especiales consultar) Terminación: Prepintado</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Instalación fijación oculta.</li>\r\n    <li>Permite una superficie limpia y estética.</li>\r\n    <li>Uso en revestimientos.</li>\r\n    <li>Largos a pedido, consultar.</li>\r\n    <li>Permite un revestimiento horizontal y vertical.</li>\r\n    <li>Solución perforada para quiebravista.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 3),
(21, 'Panel Cn-20', 2, '<p>Panel arquitectónico mayormente usado en fachadas, cielos y Terminaciones. En sus cuatro formas hacen de una buena\r\n    alternativa de estética y permite revestimientos horizontales y verticales.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 200 mm Espesores: 0.5mm / 0.6mm Largos: 0.5mt a 7.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Instalación fijación oculta, permite una superficie limpia y estética.</li>\r\n    <li>Permite una superficie limpia y estética.</li>\r\n    <li>Uso en revestimientos, cielos, malls, tiendas, fachadas.</li>\r\n    <li>Largos a pedido, consultar.</li>\r\n    <li>Permite un revestimiento horizontal y vertical.</li>\r\n    <li>4 distintos formatos lo hacen una buena alternativa para revestimiento.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 2),
(22, 'Panel Cn-B2', 2, '<p>Panel continuo, diseñado para su aplicación en revestimientos y cielos. Está constituido por una superficie de planos\r\n    ligeramente oblicuos que le otorgan un interesante efecto de luz-sombra. Sus bordes laterales están constituidos por\r\n    dos nervios tipo emballetado rigidizante. No tiene fijaciones a la vista. Puede colocarse en disposición vertical,\r\n    horizontal o diagonal. El panel es fabricado en largos continuos, conforme a la longitud especificada por proyecto.\r\n    Largo máximo 12 metros.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 450mm Espesores: 0.4mm / 0.5mm / 0.6mm. Largos: 0.5mt a 18.00 mts. (largos especiales, consultar).</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Panel CN-B2 diseñado para revestimientos y cielos según proyecto.</li>\r\n    <li>Permite su instalación en forma vertical u horizontal.</li>\r\n    <li>Se fabrica en largos a solicitud del cliente.</li>\r\n    <li>Resistencia mecánica.</li>\r\n    <li>Sistema de fijación oculta.</li>\r\n    <li>Su geometría esta constituida por una superficie ligeramente oblicua permitiendo un efecto de luz y sombra, generando estética en revestimiento.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 2),
(23, 'Celosia Cn-23', 2, '<p>Celosía conformada perfiles Zinc Alum o prepintados en variados colores, diseñado especialmente para terminaciones y\r\n    decoraciones arquitectónicas. Sus usos son tan variados como quiebravistas, muros, logias y cortinas para el control\r\n    solar y de la visión hacia interiores.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Largo máx. : 6000mm. (largos especiales, consultar) Espesores: 0.5mm / 0.6mm Material: Acero Zinc-alum o prepintado.\r\n</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Celosía formada por perfiles de zincalum con pintura de terminación en una cara, con separación variable según\r\n        el diseño del proyectista.</li>\r\n    <li>Es particularmente útil como quiebravistas en antetechos, muros, cortinas y logias cuando deben resolverse los\r\n        espacios destinados al intercambio de aire y control de visión.</li>\r\n    <li>Es también apropiado para cubrir con un elemento fuertemente cromático los espacios de cajas de escala, patios\r\n        de servicios, etc.</li>\r\n    <li>El fuerte acento de sus sombras aporta una vigorosa textura visual, que junto a la posibilidad de variación de\r\n        color, permite su utilización como elemento decorativo de contraste en las grandes superficies de revestimiento\r\n        ejecutadas con textura más lisa.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 2),
(24, 'Celosia Cn-40', 2, '<p>Celosía conformada perfiles Zinc Alum o prepintados en variados colores, diseñado especialmente para terminaciones y\r\n    decoraciones arquitectónicas. Sus usos son tan variados como quiebravistas, muros, logias y cortinas para el control\r\n    solar y de la visión hacia interiores.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Largo máx. : 6000mm (largos especiales, consultar) Espesores: 0.5mm / 0.6mm Material: acero zinc-alum o prepintado</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Celosía formada por perfiles de zincalum con pintura de terminación en una cara, con separación variable según\r\n        el diseño del proyectista.</li>\r\n    <li>Es particularmente útil como quiebravistas en antetechos, muros, cortinas y logias cuando deben resolverse los\r\n        espacios destinados al intercambio de aire y control de visión.</li>\r\n    <li>Es también apropiado para cubrir con un elemento fuertemente cromático los espacios de cajas de escala, patios\r\n        de servicios, etc.</li>\r\n    <li>El fuerte acento de sus sombras aporta una vigorosa textura visual, que junto a la posibilidad de variación de\r\n        color, permite su utilización como elemento decorativo de contraste en las grandes superficies de revestimiento\r\n        ejecutadas con textura más lisa.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 2),
(25, 'Teja Colonial Continua', 3, '<p>Cubierta habitacional de acero de largo continuo, con claras ventajas estructurales y de estanqueidad. Su sistema de\r\n    traslapo lateral corta la filtración de agua por capilaridad. - Diseño tipo colonial en diferentes tonalidades,\r\n    proporciona un carácter estético superior. - Gran vida útil de la cubierta ya que es fabricada con acero Zinc\r\n    Aluminio, más un sofisticado esquema de pintura. - Su gran avance útil y formato de largo continuo, favorece la\r\n    velocidad de montaje de la cubierta. - Dado su bajo peso, se obtiene como ventaja un mayor ahorro en la estructura\r\n    soportante y una menor carga sísmica, ya que el peso de la cubierta es un 10% menor con respecto a su símil de acero\r\n    y hasta un 40% con respecto de la teja tradicional de ladrillo.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 1020mm Espesores: 0.4mm / 0.5mm / 0.6mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.\r\n</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>El avance útil permite un mayor ahorro en m2 instalado.</li>\r\n    <li>Resistencia mecánica.</li>\r\n    <li>La instalación de cubiertas.</li>\r\n    <li>Revestimiento simple y rápida.</li>\r\n    <li>Largos a pedido (hasta 18mts.) solución largo continuo.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 3),
(26, 'Panel Cn-Tinglado', 3, '<p>Revestimiento exterior metálico de uso habitacional para fachadas de alta durabilidad y resistencia al paso del\r\n    tiempo, gracias a la estabilidad que proporciona el acero y su esquema de pintura incorporado de fábrica. El formato\r\n    continuo de panel tinglado permite suministrar un producto a la medida del muro a cubrir lo que dará a su obra un\r\n    carácter estético eficiente.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Ancho útil :1000 - Espesores: 0.4, 0.5, 0.6 mm. - Largos: Largos especiales - Terminación: Prepintado - Alto nervio:\r\n    30 mm.\r\n</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Instalación fijación oculta.</li>\r\n    <li>Permite una superficie limpia y estética.</li>\r\n    <li>Uso en revestimientos.</li>\r\n    <li>Largos a pedido, consultar.</li>\r\n    <li>Permite un revestimiento horizontal y vertical.</li>\r\n    <li>Panel de acero para revestimientos exteriores.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>\r\n\r\n<h3>Terminación</h3>\r\n<p>La pintura aplicada corresponde a poliester de alta calidad con resistencia a la humedad y a la corrosión. Esta\r\n    configuración mantiene la estabilidad en el color y el brillo por muchos años.</p>\r\n\r\n<h3>Ventajas</h3>\r\n<ul>\r\n    <li>Resistencia al impacto .</li>\r\n    <li>Aislamiento térmico al ser parte de un sistema.</li>\r\n    <li>Resistencia al fuego.</li>\r\n    <li>Estanqueidad.</li>\r\n    <li>No emite gases inflamables.</li>\r\n</ul>', 2),
(27, 'Panel Cn-5V', 3, '<p>Plancha de acero utilizada para cubierta y revestimiento la cual permite soportar cargas entre los distanciamientos\r\n    de costaneras gracias a sus nervios rigidizantes. Panel CN-5V Terminación en prepintado y zinc-alum. Panel CN-5V\r\n    Traslúcida FRP disponibles con la misma geometría para solucionar la luminocidad requerida del proyecto.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil : 819mm Espesores: 0.35 mm / 0.4mm / 0.5mm. Largos: 0.5mt a 12.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.\r\n</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Instalación de cubierta-revestimiento es simple y rápida.</li>\r\n    <li>Resistencia a la humedad corrosión.</li>\r\n    <li>Solución largo continuo cubiertas (largos especiales, consultar).</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 3),
(28, 'Panel Ondulado CV-3/4', 3, '<p>Plancha de acero acanalada de tamaño de onda 3/4”. Para cubiertas de viviendas, cobertizos, pequeños galpones,\r\n    revestimientos laterales y cierres perimetrales. Panel Ondulado CN-3/4 Terminación en prepintado y zinc-alum Panel\r\n    Ondulado CN-3/4 Traslúcida FRP disponible con la misma geometría para solucionar la luminosidad requerida del\r\n    proyecto.</p>\r\n\r\n<h3>Caracteristicas técnicas</h3>\r\n<p>Avance útil: 762mm Espesores: 0.35mm / 0.4mm / 0.5mm Largos: 0.5mt a 18.00 mts. (largos especiales, consultar) Terminación: zinc-alum o prepintado.</p>\r\n\r\n<h3>Caracteristicas del Panel</h3>\r\n<ul>\r\n    <li>Extraordinaria liviandad.</li>\r\n    <li>Alta resistencia mecánica.</li>\r\n    <li>Gran resistencia a la humedad, corrosión y medio ambiente.</li>\r\n    <li>Instalación rápida y simple.</li>\r\n    <li>Sus dimensiones permiten un fácil traslado.</li>\r\n    <li>Los largos a pedido permiten soluciones de largo continuo.</li>\r\n    <li>Superficie homogénea de limpieza fácil y rápida.</li>\r\n</ul>\r\n\r\n<h3>Recubrimiento</h3>\r\n<p>Zinc-alum aplicado en ambas caras. Según norma fabricación ASTM A792 M08 Calidad AZ-150 (150gr/m2).</p>', 2);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `tbl_products_cb`
--
ALTER TABLE `tbl_products_cb`
  ADD PRIMARY KEY (`id_product_cb`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `tbl_products_cb`
--
ALTER TABLE `tbl_products_cb`
  MODIFY `id_product_cb` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
